[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"


[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", features = [] }


[dependencies]
tracing.workspace = true
futures.workspace = true
anyhow.workspace = true
specta.workspace = true
app.workspace = true
surrealdb = { workspace = true, features = ["kv-rocksdb"] }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "=2.0.0-beta.22", features = [] }
tauri-specta = { version = "2.0.0-rc.8", features = [
    "typescript",
    "javascript",
] }


[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
macos-trampoline = { path = "./lib/macos" }
