[package]
name = "moss"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "kernel/bus",
    "kernel/fs",

    "lib/async_utl",
    "lib/seaorm_utl",
    "lib/graphql_mac",
    "lib/graphql_utl",
    "lib/mac",
    "lib/types",

    "platform/conf",
    "platform/pwd",
    "platform/workspace",
    "platform/project",
    "platform/app",

    "mossctl",
    "net",

    "view/desktop/bin",
]

[profile.release]
# This makes the compiled code faster and smaller, but it makes 
# compiling slower, so it's only enabled in release mode.
lto = false
opt-level = 3
panic = "abort"
codegen-units = 1

[profile.dev.package.sqlx-macros]
opt-level = 3


[build]
rustflags = ["-C", "target-cpu=native"]

[workspace.dependencies]
fs = { path = "kernel/fs" }
bus = { path = "kernel/bus" }
mac = { path = "lib/mac" }
async_utl = { path = "lib/async_utl" }
seaorm_utl = { path = "lib/seaorm_utl" }
graphql_utl = { path = "lib/graphql_utl" }
graphql_mac = { path = "lib/graphql_mac" }
types = { path = "lib/types" }
conf = { path = "platform/conf" }
pwd = { path = "platform/pwd" }
project = { path = "platform/project" }
workspace = { path = "platform/workspace" }
app = { path = "platform/app" }

mossctl = { path = "mossctl" }
net = { path = "net" }

clap = "4.5.4"

libc = "0.2.155"
thiserror = "1.0"
anyhow = "1.0"
bitflags = "2.5.0"
chrono = "0.4"
notify = "6.1.1"
url = "2.5.0"
nanoid = "0.4"
hashbrown = "0.7.2"
ahash = "0.8.11"
sha2 = "0.10.8"
arc-swap = "1.7.1"
radix_trie = "0.2.1"
parking_lot = "0.12.3"
derive_more = "0.99.17"
async-task = "4.7.1"
async-executor = "1.4"
ctor = "0.2.8"
strum = "0.26"
specta = "=2.0.0-rc.12"

tokio = "1"
tokio-util = "0.7"
tokio-stream = "0.1.15"
async-stream = "0.3.5"
smol = "2.0.0"

futures = "0.3"
futures-util = "0.3"

serde = "1.0"
serde_json = "1.0"
serde_with = "3.8.1"
jsonpath_lib = "0.3.0"
toml = "0.8.12"

async-trait = "0.1"
once_cell = "1.19"
lazy_static = "1.4.0"

tracing = "0.1"
opentelemetry = "0.22.0"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = "0.3.18"

surrealdb = "1.5.3"

sea-orm = "0.12"
sea-orm-migration = "0.12.0"

async-graphql = "7.0"
graphql-parser = "0.4.0"

axum = "0.7"
async-graphql-axum = "7.0"
axum-server = "0.6"
tower = "0.4"
tower-http = "0.5.2"
http = "1.1.0"
jsonwebtoken = "9.3.0"

[dependencies]
project.workspace = true
mossctl.workspace = true
anyhow.workspace = true
app.workspace = true
once_cell.workspace = true
tokio = { workspace = true, features = ["full"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
mimalloc = { version = "0.1.39", default-features = false }
